---
title: "Exercise 3 - Beamer and equations"
author: "Gerko Vink"
date: "Markup languages and reproducible programming in statistics"
output: html_document
---

---

Dear all, 

This week we will learn how to use $\LaTeX$ to create presentations and we will learn how to use $\LaTeX$ for mathematical notation. 

Let's start. 

Gerko

---

###Presentations with beamer
We use the `beamer` package to create presentations with `tex`. If all is well, you should now be able to create and compile your own `tex` documents (if not, please ask me for help!). Therefore I refer you to [this page](http://userpages.umbc.edu/~rostamia/beamer/) and to the `Beamer_Userguide.pdf` file on `BlackBoard` and in the `DropBox`. For the more tech-savvy users among you, [this](http://www.math-linux.com/latex-26/article/how-to-make-a-presentation-with-latex-introduction-to-beamer) discusses fancy stuff with `beamer`. You can simply ignore the part about `linux` and focus on the `tex` code. 

---

###`beamer` themes
The [beamer theme matrix](https://www.hartwork.org/beamer-theme-matrix/) site gives you an overview of the default beamer themes. Utrecht University also has a `beamer` theme (although unofficial), which uses the UU colors (see DropBox and BB). Let's say that it is rather yellow and leave it at that. Still, many people use it and it is a well-developed style. 

---

###Mathematical notation
Anything that is presented between `$`-signs is printed as (a) mathematical element(s). Most often, the `$` operator is used to denote in-line equations or math. For example, `$y_i = a + \beta x_i + \epsilon_i$` is printed as $y_i = a + \beta x_i + \epsilon_i$. To find out what the `tex` code for the mathematical notation elements is (and much more) have a look at the `Math Symbols` document on `BlackBoard` and in the `DropBox`.  

To present mathematical equations, use

    \begin{equation}
    y_i = a + \beta x_i + \epsilon_i
    \end{equation}

to produce

\[y_i = a + \beta x_i + \epsilon_i.\]

In `tex` these will be numbered. To omit equation numbering, use `\begin{equation*}` (which requires the `amsmath` package). 

So far the very brief intro. 

---

###Exercises
1. Study [this page](http://userpages.umbc.edu/~rostamia/beamer/) to get yourself acquainted with beamer
2. Study the `AMS example file.pdf` and `AMS example file.tex` to get yourself acquainted with mathematical notation in `tex`. 
3. Recreate the example presentation file `beamer_exercise.pdf` with beamer in $\LaTeX$. 

---

Upload the documents (at least the `.tex` and `.pdf`) from question 4 to DropBox before the next lecture. We will discuss the solution next week. As answers, I will give you the `tex` and markdown (`html` and `pdf`) solutions. 

---
